spring:
  application:
    name: molecom-backend
  profiles:
    active: local

  # 기본(Primary) 데이터소스: MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/dicom_app?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME:dev}
    password: ${MYSQL_PASSWORD:devpass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    open-in-view: false
    # 기본 EMF(MySQL)에 적용
    hibernate:
      ddl-auto: validate        # 로컬은 update 가능
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # 생략 가능(드라이버로 자동 유추)
        format_sql: true
        jdbc.time_zone: Asia/Seoul
    show-sql: false

# 보조 데이터소스: Oracle (커스텀 prefix)
app:
  datasource:
    oracle:
      url: jdbc:oracle:thin:@//210.94.241.9:1521/xe
      username: ${ORACLE_USERNAME:C##sahmyook}
      password: ${ORACLE_PASSWORD:sahmyook1}
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
  jpa:
    oracle:
      ddl-auto: validate
      show-sql: false
      properties:
        hibernate.dialect: org.hibernate.dialect.OracleDialect

  jwt:
    secret: ${JWT_SECRET:change-me-change-me-change-me-change}  # 32바이트 이상
    security:
      cors:
        allowed-origins: "http://localhost:3000,https://your-frontend.example.com"

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO

springdoc:
  api-docs.enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
