spring:
  application:
    name: molecom-backend
  profiles:
    active: local

  # 기본(Primary) 데이터소스: MySQL
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/dicom_app?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME:dev}
    password: ${MYSQL_PASSWORD:devpass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update        # 로컬에서는 update 권장, 처음 테스트는 create로 확인 가능
    show-sql: true            # 실행되는 SQL 로그 확인
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL8 기준 (버전에 맞게 지정)
        format_sql: true
        jdbc.time_zone: Asia/Seoul

# 보조 데이터소스: Oracle (커스텀 prefix)
app:
  datasource:
    oracle:
      url: jdbc:oracle:thin:@//210.94.241.9:1521/xe
      username: ${ORACLE_USERNAME:C##sahmyook}
      password: ${ORACLE_PASSWORD:sahmyook1}
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
  jpa:
    oracle:
      ddl-auto: validate
      show-sql: false
      properties:
        hibernate.dialect: org.hibernate.dialect.OracleDialect

jwt:
  secret: ${JWT_SECRET:fd471a4de6ec54a281f66c51c264a2e7}  # 32바이트 이상
  security:
    cors:
      allowed-origins: "http://localhost:3000,https://your-frontend.example.com"

cifs:
  base-url: smb://210.94.241.9/sts
  domain:         # AD 도메인 없으면 비워도 됨
  username: ${CIFS_USER:syu}
  password: ${CIFS_PASS:1}

server:
  port: 8080

logging:
  level:
    org.apache.catalina.connector.OutputBuffer: ERROR
    org.apache.catalina.core: ERROR

springdoc:
  api-docs.enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
